FROM node:20-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL=http://localhost:5173/api
ARG VITE_APP_BACKEND_URL=http://localhost:5173/api
ARG VITE_SOCKET_URL=http://localhost:5173
ARG VITE_APP_SOCKET_URL=http://localhost:5173
ARG VITE_FIREBASE_API_KEY=
ARG VITE_FIREBASE_AUTH_DOMAIN=
ARG VITE_FIREBASE_PROJECT_ID=
ARG VITE_FIREBASE_STORAGE_BUCKET=
ARG VITE_FIREBASE_MESSAGING_SENDER_ID=
ARG VITE_FIREBASE_APP_ID=

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_APP_BACKEND_URL=$VITE_APP_BACKEND_URL \
    VITE_SOCKET_URL=$VITE_SOCKET_URL \
    VITE_APP_SOCKET_URL=$VITE_APP_SOCKET_URL \
    VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 5173

HEALTHCHECK --interval=20s --timeout=5s --start-period=10s --retries=6 \
  CMD wget -qO- http://127.0.0.1:5173/ >/dev/null || exit 1
